// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: corporation_messages.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const getCorporationMessage = `-- name: GetCorporationMessage :one
SELECT
    cm.corporation_id,
    cm.message,
    cm.source_url,
    cm.updated_at,
    cm.updated_by,
    ec.name AS updated_by_name
FROM
    corporation_messages cm
    LEFT JOIN eve_characters ec ON cm.updated_by = ec.id
WHERE
    cm.corporation_id = ?
`

type GetCorporationMessageRow struct {
	CorporationID int64
	Message       string
	SourceUrl     sql.NullString
	UpdatedAt     time.Time
	UpdatedBy     sql.NullInt64
	UpdatedByName sql.NullString
}

func (q *Queries) GetCorporationMessage(ctx context.Context, corporationID int64) (GetCorporationMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getCorporationMessage, corporationID)
	var i GetCorporationMessageRow
	err := row.Scan(
		&i.CorporationID,
		&i.Message,
		&i.SourceUrl,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.UpdatedByName,
	)
	return i, err
}

const updateCorporationMessage = `-- name: UpdateCorporationMessage :one
INSERT INTO corporation_messages (
    corporation_id,
    message,
    source_url,
    updated_at,
    updated_by
)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (corporation_id) DO
UPDATE SET
    message = excluded.message,
    source_url = excluded.source_url,
    updated_at = excluded.updated_at,
    updated_by = excluded.updated_by
RETURNING corporation_id, message, source_url, updated_at, updated_by
`

type UpdateCorporationMessageParams struct {
	CorporationID int64
	Message       string
	SourceUrl     sql.NullString
	UpdatedAt     time.Time
	UpdatedBy     sql.NullInt64
}

func (q *Queries) UpdateCorporationMessage(ctx context.Context, arg UpdateCorporationMessageParams) (CorporationMessage, error) {
	row := q.db.QueryRowContext(ctx, updateCorporationMessage,
		arg.CorporationID,
		arg.Message,
		arg.SourceUrl,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	var i CorporationMessage
	err := row.Scan(
		&i.CorporationID,
		&i.Message,
		&i.SourceUrl,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
